name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    name: Pytest Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run unit tests with coverage
        run: pytest --cov-report=xml

  bandit:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit security scan
        id: run_bandit
        continue-on-error: true
        run: |
          bandit -r || true
      
        

  dependency_check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'python-app'
          path: '.'
          format: 'HTML'

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ${{github.workspace}}/reports


  dast_zap:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: dependency_check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Docker Network
        run: docker network create zap-network

      - name: Build Application Docker Image
        run: |
          
          if [ ! -f Dockerfile ]; then
            echo -e "FROM python:3.12-slim\nWORKDIR /app\nCOPY . .\nRUN pip install -r requirements.txt\nEXPOSE 8080\nCMD [\"python\", \"-m\", \"http.server\", \"8080\"]" > Dockerfile
          fi
          docker build -t my-python-app .

      - name: Run Application Container
        run: |
          docker run -d --name web-app --network zap-network -p 8080:8080 my-python-app
        
          sleep 5

      - name: Run OWASP ZAP Baseline Scan
        run: |
          
          docker run --user root --network zap-network -v ${{ github.workspace }}:/zap/wrk/:rw -t zaproxy/zaproxy:stable zap-baseline.py \
            -t http://web-app:8080 \
            -r zap_report.html

      - name: Upload ZAP DAST Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: ${{ github.workspace }}/zap_report.html